export const POKEMON_EXTRA_DATA = {
  "Turtwig": "Ruta 201 (Inicial)",
  "Grotle": "Evoluciona de Turtwig al Nvl. 18",
  "Torterra": "Evoluciona de Grotle al Nvl. 32",
  "Chimchar": "Ruta 201 (Inicial)",
  "Monferno": "Evoluciona de Chimchar al Nvl. 14",
  "Infernape": "Evoluciona de Monferno al Nvl. 36",
  "Piplup": "Ruta 201 (Inicial)",
  "Prinplup": "Evoluciona de Piplup al Nvl. 16",
  "Empoleon": "Evoluciona de Prinplup al Nvl. 36",
  "Starly": "Rutas 201, 202, 203, 204",
  "Staravia": "Evoluciona de Starly al Nvl. 14",
  "Staraptor": "Evoluciona de Staravia al Nvl. 34",
  "Bidoof": "Rutas 201, 202, 203, 204",
  "Bibarel": "Evoluciona de Bidoof al Nvl. 15",
  "Kricketot": "Rutas 202, 203, 204 (Mañana/Noche)",
  "Kricketune": "Evoluciona de Kricketot al Nvl. 10",
  "Shinx": "Rutas 202, 203, 204",
  "Luxio": "Evoluciona de Shinx al Nvl. 15",
  "Luxray": "Evoluciona de Luxio al Nvl. 30",
  "Abra": "Rutas 203, 215",
  "Kadabra": "Evoluciona de Abra al Nvl. 16",
  "Alakazam": "Evoluciona de Kadabra por Intercambio",
  "Magikarp": "Pescando en casi cualquier cuerpo de agua",
  "Gyarados": "Evoluciona de Magikarp al Nvl. 20",
  "Budew": "Rutas 204, 212, Bosque Vetusto",
  "Roselia": "Evoluciona de Budew (Amistad, Día)",
  "Roserade": "Evoluciona de Roselia (Piedra Día)",
  "Zubat": "Puerta Pirita, Senda Desolada, Monte Corona",
  "Golbat": "Evoluciona de Zubat al Nvl. 22",
  "Crobat": "Evoluciona de Golbat (Amistad)",
  "Geodude": "Rutas 206, 207, Mina Pirita",
  "Graveler": "Evoluciona de Geodude al Nvl. 25",
  "Golem": "Evoluciona de Graveler por Intercambio",
  "Onix": "Mina Pirita, Isla Hierro, Calle Victoria",
  "Steelix": "Evoluciona de Onix (Intercambio con Revestimiento Metálico)",
  "Cranidos": "Fósil Cráneo (Minería en el Subsuelo)",
  "Rampardos": "Evoluciona de Cranidos al Nvl. 30",
  "Shieldon": "Fósil Coraza (Minería en el Subsuelo)",
  "Bastiodon": "Evoluciona de Shieldon al Nvl. 30",
  "Machop": "Rutas 207, 208, 211, Monte Corona",
  "Machoke": "Evoluciona de Machop al Nvl. 28",
  "Machamp": "Evoluciona de Machoke por Intercambio",
  "Psyduck": "Senda Desolada, Puerta Pirita (Surf)",
  "Golduck": "Evoluciona de Psyduck al Nvl. 33",
  "Burmy": "Árboles de Miel",
  "Wormadam": "Evoluciona de Burmy (Hembra) al Nvl. 20",
  "Mothim": "Evoluciona de Burmy (Macho) al Nvl. 20",
  "Wurmple": "Ruta 205, Bosque Vetusto, Árboles de Miel",
  "Silcoon": "Evoluciona de Wurmple al Nvl. 7 (Según personalidad)",
  "Beautifly": "Evoluciona de Silcoon al Nvl. 10",
  "Cascoon": "Evoluciona de Wurmple al Nvl. 7 (Según personalidad)",
  "Dustox": "Evoluciona de Cascoon al Nvl. 10",
  "Combee": "Árboles de Miel",
  "Vespiquen": "Evoluciona de Combee (Hembra) al Nvl. 21",
  "Pachirisu": "Ruta 205, Valle Eólico, Forja Fuego",
  "Buizel": "Rutas 205, 213, 224, Valle Eólico",
  "Floatzel": "Evoluciona de Buizel al Nvl. 26",
  "Cherubi": "Árboles de Miel",
  "Cherrim": "Evoluciona de Cherubi al Nvl. 25",
  "Shellos": "Rutas 205, 213, 218, 224, Valle Eólico",
  "Gastrodon": "Evoluciona de Shellos al Nvl. 30",
  "Heracross": "Árboles de Miel",
  "Aipom": "Árboles de Miel",
  "Ambipom": "Evoluciona de Aipom (Subir de nivel con Doble Golpe)",
  "Drifloon": "Valle Eólico (Solo los viernes)",
  "Drifblim": "Evoluciona de Drifloon al Nvl. 28",
  "Buneary": "Bosque Vetusto",
  "Lopunny": "Evoluciona de Buneary (Amistad)",
  "Gastly": "Vieja Mansión, Torre Perdida",
  "Haunter": "Evoluciona de Gastly al Nvl. 25",
  "Gengar": "Evoluciona de Haunter por Intercambio",
  "Misdreavus": "Bosque Vetusto, Torre Perdida (Noche) [Solo Perla]",
  "Mismagius": "Evoluciona de Misdreavus (Piedra Noche)",
  "Murkrow": "Bosque Vetusto, Torre Perdida (Noche) [Solo Diamante]",
  "Honchkrow": "Evoluciona de Murkrow (Piedra Noche)",
  "Glameow": "Rutas 218, 222 [Solo Perla]",
  "Purugly": "Evoluciona de Glameow al Nvl. 38",
  "Goldeen": "Pescando en Lago Valor, Lago Verdad",
  "Seaking": "Evoluciona de Goldeen al Nvl. 33",
  "Barboach": "Rutas 205, 208, 210, 212 (Pescando)",
  "Whiscash": "Evoluciona de Barboach al Nvl. 30",
  "Chingling": "Ruta 211, Monte Corona",
  "Chimecho": "Evoluciona de Chingling (Amistad, Noche)",
  "Stunky": "Rutas 206, 214, 221 [Solo Diamante]",
  "Skuntank": "Evoluciona de Stunky al Nvl. 34",
  "Meditite": "Rutas 208, 210, 211, 216, Monte Corona",
  "Medicham": "Evoluciona de Meditite al Nvl. 37",
  "Bronzor": "Ruta 206, Cueva Extravío, Monte Corona",
  "Bronzong": "Evoluciona de Bronzor al Nvl. 33",
  "Ponyta": "Rutas 206, 210, 211, 214, 215",
  "Rapidash": "Evoluciona de Ponyta al Nvl. 40",
  "Bonsly": "Rutas 209, 210, Jardín Trofeo (Perla)",
  "Sudowoodo": "Evoluciona de Bonsly (Subir de nivel con Mimético)",
  "Mime Jr.": "Rutas 209, 210, Jardín Trofeo (Diamante)",
  "Mr. Mime": "Evoluciona de Mime Jr. (Subir de nivel con Mimético)",
  "Happiny": "Eclosionar Huevo (Ciudad Corazón), Jardín Trofeo",
  "Chansey": "Evoluciona de Happiny (Subir nivel con Piedra Oval, Día)",
  "Blissey": "Evoluciona de Chansey (Amistad)",
  "Cleffa": "Monte Corona, Jardín Trofeo",
  "Clefairy": "Evoluciona de Cleffa (Amistad)",
  "Clefable": "Evoluciona de Clefairy (Piedra Lunar)",
  "Chatot": "Rutas 213, 218, 222, 224",
  "Pichu": "Jardín Trofeo",
  "Pikachu": "Evoluciona de Pichu (Amistad)",
  "Raichu": "Evoluciona de Pikachu (Piedra Trueno)",
  "Hoothoot": "Rutas 210, 211, Bosque Vetusto (Noche)",
  "Noctowl": "Evoluciona de Hoothoot al Nvl. 20",
  "Spiritomb": "Piedra Espíritu en la Torre Sagrada + 32 interacciones Subsuelo",
  "Gible": "Cueva Extravío (Entrada oculta)",
  "Gabite": "Evoluciona de Gible al Nvl. 24",
  "Garchomp": "Evoluciona de Gabite al Nvl. 48",
  "Munchlax": "Árboles de Miel (Muy raro)",
  "Snorlax": "Evoluciona de Munchlax (Amistad)",
  "Unown": "Ruinas Sosiego",
  "Riolu": "Eclosionar Huevo entregado por Quinoa (Isla Hierro)",
  "Lucario": "Evoluciona de Riolu (Amistad, Día)",
  "Wooper": "Ruta 212, Gran Pantano",
  "Quagsire": "Evoluciona de Wooper al Nvl. 20",
  "Wingull": "Rutas 213, 218, 219, 220, 221, 222 (Surf)",
  "Pelipper": "Evoluciona de Wingull al Nvl. 25",
  "Girafarig": "Ruta 214, Orilla Valor",
  "Hippopotas": "Cueva Ruinamaníaco",
  "Hippowdon": "Evoluciona de Hippopotas al Nvl. 34",
  "Azurill": "Gran Pantano, Jardín Trofeo",
  "Marill": "Evoluciona de Azurill (Amistad)",
  "Azumarill": "Evoluciona de Marill al Nvl. 18",
  "Skorupi": "Gran Pantano",
  "Drapion": "Evoluciona de Skorupi al Nvl. 40",
  "Croagunk": "Gran Pantano",
  "Toxicroak": "Evoluciona de Croagunk al Nvl. 37",
  "Carnivine": "Gran Pantano",
  "Remoraid": "Rutas 213, 222, 223, 224 (Pescando)",
  "Octillery": "Evoluciona de Remoraid al Nvl. 25",
  "Finneon": "Rutas 205, 218, 219, 220, 221 (Pescando)",
  "Lumineon": "Evoluciona de Finneon al Nvl. 31",
  "Tentacool": "Rutas 205, 213, 218, 219, 220, 221 (Surf)",
  "Tentacruel": "Evoluciona de Tentacool al Nvl. 30",
  "Feebas": "Monte Corona (Pescando en 4 casillas aleatorias diarias)",
  "Milotic": "Evoluciona de Feebas (Belleza al máximo)",
  "Mantyke": "Ruta 223 (Surf)",
  "Mantine": "Evoluciona de Mantyke (Subir de nivel con Remoraid en equipo)",
  "Snover": "Rutas 216, 217, Orilla Agudeza, Monte Corona",
  "Abomasnow": "Evoluciona de Snover al Nvl. 40",
  "Sneasel": "Rutas 216, 217, Orilla Agudeza, Templo Puntaneva",
  "Weavile": "Evoluciona de Sneasel (Subir de nivel con Garra Afilada, Noche)",
  "Magnezone": "Evoluciona de Magneton (Subir de nivel en el Monte Corona)",
  "Lickilicky": "Evoluciona de Lickitung (Subir de nivel con el ataque Desenrollar)",
  "Rhyperior": "Evoluciona de Rhydon (Intercambio con Protector)",
  "Tangrowth": "Evoluciona de Tangela (Subir de nivel con el ataque Poder Pasado)",
  "Electivire": "Evoluciona de Electabuzz (Intercambio con Electrizador)",
  "Magmortar": "Evoluciona de Magmar (Intercambio con Magmatizador)",
  "Togekiss": "Evoluciona de Togetic (Piedra Día)",
  "Yanmega": "Evoluciona de Yanma (Subir de nivel con el ataque Poder Pasado)",
  "Leafeon": "Evoluciona de Eevee (Subir de nivel junto a la Roca Musgo - Bosque Vetusto)",
  "Glaceon": "Evoluciona de Eevee (Subir de nivel junto a la Roca Hielo - Ruta 217)",
  "Gliscor": "Evoluciona de Gligar (Subir de nivel con Colmillo Agudo, Noche)",
  "Mamoswine": "Evoluciona de Piloswine (Subir de nivel con el ataque Poder Pasado)",
  "Porygon-Z": "Evoluciona de Porygon2 (Intercambio con Disco Extraño)",
  "Gallade": "Evoluciona de Kirlia (Macho) (Piedra Alba)",
  "Probopass": "Evoluciona de Nosepass (Subir de nivel en el Monte Corona)",
  "Dusknoir": "Evoluciona de Dusclops (Intercambio con Tela Terrible)",
  "Froslass": "Evoluciona de Snorunt (Hembra) (Piedra Alba)",
  "Rotom": "Vieja Mansión (Televisor de noche)",
  "Uxie": "Lago Agudeza",
  "Mesprit": "Lago Verdad (Luego deambula por Sinnoh)",
  "Azelf": "Lago Valor",
  "Dialga": "Columna Lanza (Edición Diamante)",
  "Palkia": "Columna Lanza (Edición Perla)",
  "Heatran": "Montaña Dura (Postgame)",
  "Regigigas": "Templo Puntaneva (Postgame, requiere llevar a Regirock, Regice y Registeel)",
  "Giratina": "Cueva Retorno (Postgame)",
  "Cresselia": "Isla Plenilunio (Postgame, luego deambula por Sinnoh)",
  "Phione": "Criando a Manaphy con Ditto",
  "Mewtwo": "Parque Hansa (Sala Genética - Postgame)",
  "Rayquaza": "Parque Hansa (Sala Cielos - Postgame)",
  "Latias": "Parque Hansa (Sala Corazón - Postgame)",
  "Latios": "Parque Hansa (Sala Corazón - Postgame)",
  "Kyogre": "Parque Hansa (Sala Océano - Postgame)",
  "Groudon": "Parque Hansa (Sala Continente - Postgame)",
  "Regirock": "Parque Hansa (Sala Inicio - Postgame)",
  "Regice": "Parque Hansa (Sala Inicio - Postgame)",
  "Registeel": "Parque Hansa (Sala Inicio - Postgame)",
  "Ho-Oh": "Parque Hansa (Sala Arcoíris - Exclusivo Diamante Brillante)",
  "Raikou": "Parque Hansa (Sala Johto - Exclusivo Diamante Brillante)",
  "Entei": "Parque Hansa (Sala Johto - Exclusivo Diamante Brillante)",
  "Suicune": "Parque Hansa (Sala Johto - Exclusivo Diamante Brillante)",
  "Lugia": "Parque Hansa (Sala Tormenta - Exclusivo Perla Reluciente)",
  "Articuno": "Parque Hansa (Sala Kanto - Exclusivo Perla Reluciente)",
  "Zapdos": "Parque Hansa (Sala Kanto - Exclusivo Perla Reluciente)",
  "Moltres": "Parque Hansa (Sala Kanto - Exclusivo Perla Reluciente)",
  "Manaphy": "Eclosionar Huevo transferido de Pokémon Ranger",
  "Darkrai": "Isla Lunanueva (Evento: Carné Socio)",
  "Shaymin": "Paraíso Floral (Evento: Carta de Oak)",
  "Arceus": "Sala del Origen (Evento: Flauta Azur)"
};
